### PR TITLE
checkbox-bindings

### PR DESCRIPTION
**Pull request by tatchi**
I basically copied all the existing bindings from [here](https://github.com/reason-react-native/reason-react-native/blob/master/reason-react-native/src/components/CheckBox.re) and only had to address the [tintColors](https://github.com/react-native-community/react-native-checkbox#props) prop which was not present yet.

Is the binding for this prop correct? Here's how we use it:

```reason
<ReactNativeCheckbox
  tintColors={ReactNativeCheckbox.tintColor(
    ~true_=ReactNative.Color.aliceblue,
    (),
  )}
/>
``` 

Also what about the component name? Are we gonna prefix all the packages with `ReactNative`? Or is it only tempory until we remove the "legacy" ones?

### CODE REVIEW

**Review by MoOx — APPROVED** [review]
Looks good to me. I will just wait for @cknitt review as I know he might have a word to say about `@bs.deriving abstract` vs `bs.ojb`.

Also, I will probably adjust repo a little bit before release, by introducing a changelog, code of conduct etc, like in core repo, right after making the template so all repo are in sync!

**Comment by MoOx** [comment]
poke @cknitt

**Comment by cknitt** [comment]
I'd prefer `[@bs.obj]`, and I'd also prefer the type and creation function to be named `tintColors`, not `tintColor`.

**Comment by sgny** [comment]
@tatchi @MoOx @cknitt 
Sorry guys, I didn't notice this PR and thinking this was forgotten, pushed my version. I have undid that but prepared a PR for reference.

**Comment by tatchi** [comment]
Hello,

I pushed my changes to use `bs.obj`. Let me know if you prefer to merge @sgny's PR (which seems more complete) and I'll close mine :)

**Pull request merged**
